core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/>', views.cart_remove, name='cart_remove'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('info', views.info, name='info'),
    path('contacts', views.contacts, name='contacts'),
    # TODO rename to 'catalog'?
    path('catalog/', views.product_list, name='product_list'),
    # TODO rename to 'category'?
    path('catalog/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

core/shop/models.py
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='categorys/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    def quantity_choices(self):
        return [(i, str(i)) for i in range(1, self.quantity+1)]

    def __str__(self):
        return f'{self.name} | {self.price}'

    def save(self, *args, **kwargs):
        if self.quantity <= 0:
            self.available = False
        super().save(*args, **kwargs)


class ShopContacts(models.Model):
    name = models.CharField(max_length=200, default='Контактная информация')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return 'Контактная информация'


class ShopEmail(models.Model):
    shop = models.ForeignKey(ShopContacts,
                             related_name='emails',
                             on_delete=models.CASCADE)
    email = models.EmailField(verbose_name='Эл. почта', )
    desc = models.CharField(verbose_name='Краткое описание', max_length=250,
                            unique=False, null=True, blank=True)

    class Meta:
        verbose_name = 'Эл. почта'
        verbose_name_plural = 'Эл. почты'

    def __str__(self):
        return f'{self.email}'


class ShopPhoneNumber(models.Model):
    shop = models.ForeignKey(ShopContacts,
                             related_name='phones',
                             on_delete=models.CASCADE)
    phone = PhoneNumberField(verbose_name='Номер телефона',
                             unique=False, null=False, blank=False)

    class Meta:
        verbose_name = 'Тел. номер'
        verbose_name_plural = 'Тел. номера'

    def __str__(self):
        return f'{self.phone}'


class ShopAddress(models.Model):
    shop = models.ForeignKey(ShopContacts,
                             related_name='addresses',
                             on_delete=models.CASCADE)
    country = models.CharField(verbose_name='Страна', max_length=50,
                               unique=False, null=False, blank=False)
    city = models.CharField(verbose_name='Город', max_length=50,
                            unique=False, null=False, blank=False)
    street = models.CharField(verbose_name='Улица', max_length=100,
                              unique=False, null=False, blank=False)
    building = models.CharField(verbose_name='Дом/Строение', max_length=10,
                                unique=False, null=False, blank=False)
    apartment = models.CharField(verbose_name='Квартира/Комната', max_length=10,
                                 unique=False, null=True, blank=True)
    postal_code = models.CharField(verbose_name='Почтовый индекс', max_length=10,
                                   unique=False, null=True, blank=True)

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'

    def __str__(self):
        return f'{self.country}, {self.city}, ул. {self.street}, {self.building}/{self.apartment}, {self.postal_code}'

core/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage

from cart.forms import CartAddProductForm
from .models import Category, Product
from .services import get_most_filled_categories


def index(request):
    context = {
        'most_filed_categories': get_most_filled_categories(3),
    }
    return render(request, 'shop/index.html', context=context)


def about(request):
    return render(request, 'shop/about.html', {})


def info(request):
    return render(request, 'shop/info.html', {})


def contacts(request):
    return render(request, 'shop/contacts.html', {})


def product_list(request, category_slug=None):
    sort = request.GET.get('sort')
    page_no = int(request.GET.get('page', 1))
    categories = Category.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = category.products.all().filter(available=True)
    else:
        category = None
        products = Product.objects.filter(available=True)

    if sort:
        products = sorted(products,
                          key=lambda product: product.price,
                          reverse=sort=='desc')

    paginator = Paginator(products, 16)
    try:
        page = paginator.page(page_no)
    except EmptyPage:
        page_no = 1
        page = paginator.page(page_no)
    pages_around = list(filter(lambda x: x > 0 and x <= paginator.num_pages, range(page_no-5//2, page_no+5//2+1)))

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': page.object_list,
                   'page': page,
                   'pages_around': pages_around,
                   'sort': sort})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm(product_quantity_choices=product.quantity_choices())
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'is_incart': 0, })

core/templates/shop/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <div class="container dark-grey-text mt-3">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
          <div class="container-fluid">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'shop:index' %}">Главная</a></li>
                <li class="breadcrumb-item"><a href="{% url 'shop:product_list' %}">Каталог</a></li>
                <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
              </ol>
            </nav>
          </div>
        </nav>
        <div class="shadow-4 bg-white rounded-5 mb-4 overflow-hidden d-xl-block">
          <div class="row wow fadeIn">
            <div class="col-md-6 mb-4">
                <img src="{% if product.image %}
                              {{ product.image.url }}
                          {% else %}
                              {% static 'img/no_image.png' %}
                          {% endif %}"
                    class="img-fluid product-detail">
            </div>
            <div class="col-md-6 mb-4">
              <div class="p-4">
                <div class="mb-3">
                  <a class="" href="{{ product.category.get_absolute_url }}">
                    <span class="badge bg-dark">{{ product.category.name }}</span>
                  </a>
                </div>
                <p class="lead">
                  <span>BYN {{ product.price }}</span>
                </p>
                <p class="lead font-weight-bold">{{ product.name }}</p>
                  {% if cart|is_incart:product %}
                <a href="{% url 'cart:cart_detail' %}" class="btn btn-primary btn-sm">
                    В корзине
                </a>
                {% else %}
                <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                  {{ cart_product_form }}
                  {% csrf_token %}
                  <input type="submit" class="btn btn-primary btn-sm" value="В корзину">
                </form>
                {% endif %}
                <p>{{ product.description|linebreaks }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

core/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Все категории{% endif %}
{% endblock %}

{% block content %}
<div class="container pt-5">
    <div class="row gx-xl-3">
      <div class="col-xl-2 mb-4 mb-lg-0">
        <section>
          <div class="mb-7">
          </div>
          <div class="list-group mb-5" id="list-tab" role="tablist">
            <div class="btn-group-vertical">
              <a href="{% url 'shop:product_list' %}" class="btn btn-light {% if not category %}active{% endif %}">Все категории</a>
              {% for c in categories %}
                <a href="{{ c.get_absolute_url }}" class="btn btn-light {% if c.name == category.name %}active{% endif %}">{{ c.name }}</a>
              {% endfor %}
            </div>
        </div>
        </section>
      </div>
      <div class="col-xl-10 mb-4 mb-lg-0">
        <section class="mb-6">
              <div class="btn-group mb-4">
                <button type="button" class="btn btn-light dropdown-toggle" data-mdb-toggle="dropdown" aria-expanded="false">
                  {% if sort == 'asc' %}
                    Цена: по возрастанию
                  {% elif sort == 'desc' %}
                    Цена: по убыванию
                  {% else %}
                    Сортировка
                  {% endif %}
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item"
                       href="?sort=asc">
                      Цена: По возрастанию
                    </a></li>
                  <li><a class="dropdown-item"
                       href="?sort=desc">
                      Цена: По убыванию
                    </a></li>
                </ul>
                {% if sort %}<a class="btn btn-light" href="?"><i class="fas fa-times"></i></a>{% endif %}
              </div>

              <div class="row row-cols-1 row-cols-md-4 g-4 mb-4">
              {% for product in products %}
                <div class="col">
                  <div class="card h-100">
                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="card-img-top"/>
                      <a href="{{ product.get_absolute_url }}">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                      </a>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">BYN {{ product.price }}</h5>
                      <a href="{{ product.get_absolute_url }}" class="mb-1 text-reset d-block"><p class="card-text">{{ product.name }}</p></a>
                      <p class="text-muted mb-3">{{ product.category.name }}</p>
                    </div>
                  </div>
                </div>
              {% endfor %}
              </div>

            {% if page.has_other_pages %}
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                {% if page.has_previous %}
                <li class="page-item">
                  <a class="page-link page-item"
                     href="{% if sort %}?sort={{ sort }}&page={% else %}?page={% endif %}{{ page.previous_page_number }}"
                  >
                    <i class="fas fa-chevron-left"></i>
                  </a>
                </li>
                {% endif %}
                {% for n in pages_around %}
                <li class="page-item {% if n == page.number %}active{% endif %}">
                  <a class="page-link"
                     href="{% if sort %}?sort={{ sort }}&page={% else %}?page={% endif %}{{n}}">
                    {{ n }}
                  </a>
                </li>
                {% endfor %}
                {% if page.has_next %}
                <li class="page-item">
                  <a class="page-link page-item"
                     href="{% if sort %}?sort={{ sort }}&page={% else %}?page={% endif %}{{ page.next_page_number }}"
                  >
                    <i class="fas fa-chevron-right"></i>
                  </a>
                </li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </section>
      </div>
    </div>
  </div>
{% endblock %}