core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/>', views.cart_remove, name='cart_remove'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

core/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('info', views.info, name='info'),
    path('contacts', views.contacts, name='contacts'),
    # TODO rename to 'catalog'?
    path('catalog/', views.product_list, name='product_list'),
    # TODO rename to 'category'?
    path('catalog/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

core/cart/models.py
from django.db import models

# Create your models here.

core/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):

    def __init__(self, *args, **kwargs, ):
        product_quantity_choices = kwargs.pop('product_quantity_choices', ())
        super().__init__(*args, **kwargs)
        if product_quantity_choices:
            self.fields['quantity'].choices = product_quantity_choices

    quantity = forms.TypedChoiceField(choices=[(1, '1')], coerce=int,)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

core/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST, product_quantity_choices=product.quantity_choices())
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'], )
        return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True, }, product_quantity_choices=item['product'].quantity_choices())
    return render(request, 'cart/detail.html', {'cart': cart})

core/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Ваша корзина
{% endblock %}

{% block content %}
<div class="container my-5">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>Ваша корзина</strong>
      </h5>
    </div>
    <div class="card-body">
      <!-- Section: Design block -->
      <section class="">
      <div class="row gx-lg-5">
        <div class="col-lg-8 mb-4 mb-md-0">
          <!-- Section: Product list -->
          <section class="mb-5">
            {% for item in cart %}
              {% with product=item.product error=item.error %}
              <!-- Single item -->
              <div class="row border-bottom mb-4">
                <div class="col-md-2 mb-4 mb-md-0">
                  <div
                       class="
                              bg-image
                              ripple
                              rounded-5
                              mb-4
                              overflow-hidden
                              d-block
                              "
                       data-ripple-color="light"
                       >
                    <img
                         src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                         class="w-100"
                         alt=""
                         />
                    <a href="{{ product.get_absolute_url }}">
                      <div class="hover-overlay">
                        <div
                             class="mask"
                             style="background-color: hsla(0, 0%, 98.4%, 0.2)"
                             ></div>
                      </div>
                    </a>
                  </div>
                </div>

                <div class="col-md-8 mb-4 mb-md-0">
                  <p class="fw-bold">{{ product.name }}</p>
                  <p class="mb-1">
                    <span class="text-muted me-2">Цена за ед.:</span><span>{{ product.price }}</span>
                  </p>
                  <p>
                    <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                      <span class="text-muted me-2">Количество:</span>
                      {{ item.update_quantity_form.quantity }}
                      {{ item.update_quantity_form.override }}
                      <button type="submit" class="btn btn-outline-dark btn-sm">
                        Применить
<!--                        <i class="fas fa-check"></i>-->
                      </button>
                      {% csrf_token %}
                    </form>
                    {% if error %}
                    <p>
                      {{ error|linebreaks }}
                    </p>
                    {% endif %}
                  </p>
                  <h5 class="mb-2">
                    <span class="align-middle">Итого: {{ item.total_price }}</span>
                  </h5>
                </div>

                <div class="col-md-2 mb-4 mb-md-0">
                  <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                    <button type="submit" class="btn btn-outline-danger btn-floating btn-sm">
                      <i class="fas fa-times"></i>
                    </button>
                    {% csrf_token %}
                  </form>
                </div>
              </div>
              <!-- Single item -->
                {% endwith %}
              {% endfor %}
          </section>
          <!-- Section: Product list -->
        </div>

        <div class="col-lg-4 mb-4 mb-md-0">
          <!-- Section: Summary -->
          <section class="shadow-4 p-4 rounded-5 mb-4">
            <h5 class="mb-5">Общая сумма</h5>

            <div class="d-flex justify-content-between mb-3">
              <span>Цена товаров </span>
              <span>BYN {{ cart.get_total_price }}</span>
            </div>
            <p class="text-right">
              <a href="{% url 'shop:product_list' %}" class="btn btn-light" data-mdb-ripple-color="dark">Продолжить покупки</a>
              <a href="{% url 'orders:order_create' %}" class="btn btn-light {% if not cart %}disabled{% endif %}" data-mdb-ripple-color="dark">
                Оформить
              </a>
            </p>
          </section>
          <!-- Section: Summary -->
        </div>
      </div>
    </section>
    </div>
  </div>
</div>

<p>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li>{{ message|linebreaks }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</p>
{% endblock %}